theme: jekyll-theme-cayman
title: "quickshift: Parallel GPU Image Segmentation"
description: "A project created by Sandy Jiang and Priscilla Tai for 15-418: Parallel Computer Architecture and Programming at Carnegie Mellon University."
final: index
