theme: jekyll-theme-cayman
title: Parallel GPU Image Segmentation
description: 15-418 Final Project, by Sandy Jiang (sandraj) and Priscilla Tai (ptai)
final: index
checkpoint: checkpoint
proposal: proposal